export interface CatalogService {
  name: string;
  items: string[];
}

export const servicesCatalog: CatalogService[] = [
  {
    name: "Website Development",
    items: [
      "Business Website",
      "Corporate Website",
      "Ecommerce Website",
      "Shopify Website",
      "WordPress Website",
      "Landing Page",
      "Portfolio Website",
      "Website Maintenance",
      "Website Security",
      "Website Speed Optimization",
      "Domain & Hosting Support",
    ],
  },
  {
    name: "Ecommerce Management",
    items: [
      "Shopify Management",
      "Amazon Management",
      "Flipkart Management",
      "Meesho Management",
      "JioMart",
      "IndiaMART",
      "TradeIndia",
      "ONDC",
      "Product Listing",
      "Inventory Management",
      "Order Management",
      "Offer & Coupon Management",
      "SEO",
      "Marketplace Optimization",
    ],
  },
  {
    name: "Performance Marketing",
    items: [
      "Facebook Ads",
      "Instagram Ads",
      "Meta Ads",
      "Google Ads",
      "Google Search Ads",
      "Display Ads",
      "YouTube Ads",
      "Shopping Ads",
      "Lead Generation",
      "Remarketing",
      "Pixel Setup",
      "Conversion Tracking",
      "GA4 Setup",
      "Campaign Optimization",
    ],
  },
  {
    name: "Social Media Management",
    items: [
      "Facebook",
      "Instagram",
      "LinkedIn",
      "X (Twitter)",
      "Pinterest",
      "Threads",
      "WhatsApp Channel",
      "Telegram",
      "YouTube",
      "Monthly Content Calendar",
      "Creative Designing",
      "Post Designing",
      "Reel Editing",
      "Shorts",
      "Caption Writing",
      "Hashtag Research",
      "Community Management",
      "Monthly Report",
    ],
  },
  {
    name: "SEO",
    items: [
      "Technical SEO",
      "On Page SEO",
      "Off Page SEO",
      "Local SEO",
      "Keyword Research",
      "Blog Writing",
      "Search Console",
      "Google Analytics",
      "SEO Reports",
    ],
  },
  {
    name: "Google Business Profile",
    items: [
      "Setup",
      "Optimization",
      "Posts",
      "Photo Updates",
      "Review Replies",
      "Products",
      "Q&A",
      "Monthly Report",
    ],
  },
  {
    name: "Graphic Design",
    items: [
      "Logo",
      "Poster",
      "Banner",
      "Brochure",
      "Visiting Card",
      "Social Media Creatives",
      "Product Images",
      "Packaging Design",
      "Amazon Images",
    ],
  },
  {
    name: "Video Production",
    items: [
      "Reels",
      "Shorts",
      "Product Videos",
      "Promotional Videos",
      "Motion Graphics",
      "Advertisement Videos",
    ],
  },
  {
    name: "Branding",
    items: [
      "Brand Identity",
      "Brand Strategy",
      "Competitor Analysis",
      "Marketing Planning",
      "Monthly Consultation",
    ],
  },
  {
    name: "CRM & Automation",
    items: [
      "CRM Development",
      "Lead Management",
      "Sales Pipeline",
      "Employee Management",
      "WhatsApp Automation",
      "Email Automation",
      "Reports",
      "Analytics",
    ],
  },
];

export const categoryAccent: Record<string, string> = {
  "Website Development": "oklch(0.62 0.22 285)",
  "Ecommerce Management": "oklch(0.7 0.2 55)",
  "Performance Marketing": "oklch(0.6 0.24 27)",
  "Social Media Management": "oklch(0.62 0.22 320)",
  "SEO": "oklch(0.65 0.17 155)",
  "Google Business Profile": "oklch(0.72 0.18 90)",
  "Graphic Design": "oklch(0.68 0.18 200)",
  "Video Production": "oklch(0.55 0.22 260)",
  "Branding": "oklch(0.5 0.22 300)",
  "CRM & Automation": "oklch(0.55 0.2 220)",
};